package com.github.ankurpathak;

import org.jxls.area.Area;
import org.jxls.builder.AreaBuilder;
import org.jxls.builder.xml.XmlAreaBuilder;
import org.jxls.common.CellRef;
import org.jxls.common.Context;
import org.jxls.transform.Transformer;
import org.jxls.util.TransformerFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.*;

import static com.github.ankurpathak.FinancialVertical.CAMKeys.*;

/**
 * Hello world!
 *
 *
 */
public class FinancialVertical
{

    static Logger logger = LoggerFactory.getLogger(FinancialVertical.class);
    private static final String template = "financial.xls";
    private static final String xmlConfig = "financial.xml";
    private static final String output = "target/financial_output.xls";
    public static void main( String[] args ) throws Exception
    {
        logger.info("Opening input stream");
        try(InputStream is = FinancialVertical.class.getResourceAsStream(template)) {
            try (OutputStream os = new FileOutputStream(output)) {
                Transformer transformer = TransformerFactory.createTransformer(is, os);
                System.out.println("Creating areas");
                InputStream configInputStream = FinancialVertical.class.getResourceAsStream(xmlConfig);
                AreaBuilder areaBuilder = new XmlAreaBuilder(configInputStream, transformer);
                List<Area> xlsAreaList = areaBuilder.build();
                Area xlsArea = xlsAreaList.get(0);
                Context context = new Context();
                List<Map<String, String>> aFinancials = new ArrayList<>();
                aFinancials.add(prepareFinancial());
                aFinancials.add(prepareFinancial());
                aFinancials.add(prepareFinancial());


                List<Map<String, String>> aGrowths = new ArrayList<>();
                aGrowths.add(prepareGrowth());
                aGrowths.add(prepareGrowth());


                context.putVar("aFinancials", aFinancials);
                context.putVar("aGrowths", aGrowths);
                logger.info("Applying first area at cell " + new CellRef("Template!A1"));
                xlsArea.applyAt(new CellRef("Template!A1"), context);
                xlsArea.processFormulas();
                logger.info("Complete");
                transformer.write();
                logger.info("written to file");
            }
        }
    }


    public interface  CAMKeys {
        String aFinancial = "aFinancial";
        String aYears = "aYears";
        String oSales = "oSales";
        String oExciseDuty = "oExciseDuty";
        String oNetSales = "oNetSales";
        String oExportIncentives = "oExportIncentives";
        String oTotalOperatingIncome = "oTotalOperatingIncome";
        String oRawMaterialsImported = "oRawMaterialsImported";
        String oOtherMfgExpenses = "oOtherMfgExpenses";
        String oRepairsAndMaintenance = "oRepairsAndMaintenance";
        String oCostOfGoodsSold = "oCostOfGoodsSold";
        String oGrossProfits = "oGrossProfits";
        String oSellingGeneralAdmExpenses = "oSellingGeneralAdmExpenses";
        String oMiscExpensesWrittenOff = "oMiscExpensesWrittenOff";
        String oTransportOrCartage = "oTransportOrCartage";
        String oOpbdit = "oOpbdit";
        String oOpbit = "oOpbit";
        String oInterestAndOtherFinanceCharges = "oInterestAndOtherFinanceCharges";
        String oOpbt = "oOpbt";
        String oTotalNonOperatingIncome = "oTotalNonOperatingIncome";
        String oTotalNonOperatingExpense = "oTotalNonOperatingExpense";
        String oPBT = "oPBT";
        String oTaxPaid = "oTaxPaid";
        String oPAT = "oPAT";
        String oAdjPat = "oAdjPat";
        String oEquityDividendPaid = "oEquityDividendPaid";
        String oPartnersWithDrawl = "oPartnersWithDrawl";
        String oDividendTax = "oDividendTax";
        String oDividendPreference = "oDividendPreference";
        String oRetainedProfit = "oRetainedProfit";
        String oShareCapitalPaidUp = "oShareCapitalPaidUp";
        String oSharePremiumAcc = "oSharePremiumAcc";
        String oTotalShareCapital = "oTotalShareCapital";
        String oRevaluationReserve = "oRevaluationReserve";
        String oOtherReserves = "oOtherReserves";
        String oMiscExpNotWrittenOff = "oMiscExpNotWrittenOff";
        String oTotalNetWorth = "oTotalNetWorth";
        String oBorrowingsFromAffiliatesAssociates = "oBorrowingsFromAffiliatesAssociates";
        String oShortTermBorrowingsFromOthers = "oShortTermBorrowingsFromOthers";
        String oOtherTermLiabilities = "oOtherTermLiabilities";
        String oBorrowingsFromSubsidiaries = "oBorrowingsFromSubsidiaries";
        String oDeferedTaxLiability = "oDeferedTaxLiability";
        String oLongTermProvision = "oLongTermProvision";
        String oTotalTermLiabilities = "oTotalTermLiabilities";
        String oShortTermBorrowingsFromAssociates = "oShortTermBorrowingsFromAssociates";
        String oCreditorsandBillsPayable = "oCreditorsandBillsPayable";
        String oWorkingCapitalLimitfromBanks = "oWorkingCapitalLimitfromBanks";
        String oTotalRepaymentsDueWithinYear = "oTotalRepaymentsDueWithinYear";
        String oOtherCurrLiabilitiesAndProvisions = "oOtherCurrLiabilitiesAndProvisions";
        String oProvisionForTaxation = "oProvisionForTaxation";
        String oOthercurrentLiability1 = "oOthercurrentLiability1";
        String oOthercurrentLiability2 = "oOthercurrentLiability2";
        String oOthercurrentLiability3 = "oOthercurrentLiability3";
        String oCurrentLiabilities = "oCurrentLiabilities";
        String oTotalLiabilities = "oTotalLiabilities";
        String oBalanceSheetTotal = "oBalanceSheetTotal";
        String oGrossBlock = "oGrossBlock";
        String oAccumulatedDepreciation = "oAccumulatedDepreciation";
        String oNetBlock = "oNetBlock";
        String oCapitalWip = "oCapitalWip";
        String oDeferredRevenueExpenditure = "oDeferredRevenueExpenditure";
        String oGovtAndOtherSecurities = "oGovtAndOtherSecurities";
        String oTotalOtherNonCurrentAssets = "oTotalOtherNonCurrentAssets";
        String oDebtorsMoreThanSixMonths = "oDebtorsMoreThanSixMonths";
        String oLoansAndAdvancess = "oLoansAndAdvancess";
        String oFixedDepositsWithBanks = "oFixedDepositsWithBanks";
        String oOtherNonCurrentAssets = "oOtherNonCurrentAssets";
        String oDeferredTaxAsset = "oDeferredTaxAsset";
        String oTotalCurrentAssets = "oTotalCurrentAssets";
        String oTotalInventory = "oTotalInventory";
        String oReceivablesOtherThanDeferred = "oReceivablesOtherThanDeferred";
        String oDeferredReceivables = "oDeferredReceivables";
        String oCashAndBankBalances = "oCashAndBankBalances";
        String oOtherCurrentAssets = "oOtherCurrentAssets";
        String oAdvancesToSuppliers = "oAdvancesToSuppliers";
        String oOthercurrentAsset1 = "oOthercurrentAsset1";
        String oOthercurrentAsset2 = "oOthercurrentAsset2";
        String oOthercurrentAsset3 = "oOthercurrentAsset3";
        String oTotalAssets = "oTotalAssets";
        String oDifferenceFields = "oDifferenceFields";
        String TOLTNW = "TOLTNW";
        String RETURNONCAPITALEMPLOYED = "RETURNONCAPITALEMPLOYED";
        String EBIDTABYSALES = "EBIDTABYSALES";
        String EBIDTAINTEREST = "EBIDTAINTEREST";
        String ASSETTURNOVERRATIO = "ASSETTURNOVERRATIO";
        String CREDITORSTURNOVER = "CREDITORSTURNOVER" ;
        String NETWORKINGCAPITAL = "NETWORKINGCAPITAL";
        String AVGCOLLECTIONPERIOD = "AVGCOLLECTIONPERIOD" ;
        String AVERAGEDAYS = "AVERAGEDAYS";
        String INVENTORYTOCOSTOFGOODSSOLD = "INVENTORYTOCOSTOFGOODSSOLD";
        String CURRENTRATIO = "CURRENTRATIO";
        String LIQUIDITYRATIO = "LIQUIDITYRATIO";
        String LONGDEBTTOEQUITY = "LONGDEBTTOEQUITY";
        String EQUITY = "EQUITY";
        String INTERSETCOVERAGERATIO = "INTERSETCOVERAGERATIO";
        String DSCR = "DSCR";
        String GROSSMARGINS = "GROSSMARGINS";
        String NETPROFITRATIO = "NETPROFITRATIO";
        String CASHPROFITBYRATIO = "CASHPROFITBYRATIO";
        String GROWTHINSALES = "GROWTHINSALES";
        String GROWTHINPAT = "GROWTHINPAT";
        String CASHACCRUALS = "CASHACCRUALS";
        String oNetProfitAfterTax = "oNetProfitAfterTax";
        String oDepreciation = "oDepreciation";
        String oSalaryPaidPromPartner = "oSalaryPaidPromPartner";
        String oInterestPaidPromoters = "oInterestPaidPromoters";
        String oProvisionTax = "oProvisionTax";
        String oInterest = "oInterest";
        String oOtherIncome = "oOtherIncome";
        String oOperatingCashProfit = "oOperatingCashProfit";
        String oTradeOtherReceivable = "oTradeOtherReceivable";
        String oInventories = "oInventories";
        String oLoanAdvance = "oLoanAdvance";
        String oOtherCurrentLiabilities = "oOtherCurrentLiabilities";
        String oWorkingCapitalChanges = "oWorkingCapitalChanges";
        String oCashGenratedOperations = "oCashGenratedOperations";
        String oTaxesPaid = "oTaxesPaid";
        String oNetCashOperations = "oNetCashOperations";
    }

    public static Map<String, String> prepareFinancial(){
        Map<String, String> aFinancial = new HashMap<>();
        aFinancial.put(CAMKeys.aFinancial, "Hello");

        aFinancial.put(CAMKeys.aYears, "Hello");
        aFinancial.put(CAMKeys.oSales, "Hello");
        aFinancial.put(CAMKeys.oExciseDuty, "Hello");
        aFinancial.put(CAMKeys.oNetSales, "Hello");
        aFinancial.put(CAMKeys.oExportIncentives, "Hello");
        aFinancial.put(CAMKeys.oTotalOperatingIncome, "Hello");

        aFinancial.put(CAMKeys.oRawMaterialsImported, "Hello");
        aFinancial.put(CAMKeys.oOtherMfgExpenses, "Hello");
        aFinancial.put(CAMKeys.oRepairsAndMaintenance, "Hello");
        aFinancial.put(CAMKeys.oCostOfGoodsSold, "Hello");
        aFinancial.put(CAMKeys.oCostOfGoodsSold, "Hello");
        aFinancial.put(CAMKeys.oGrossProfits, "Hello");
        aFinancial.put(CAMKeys.oSellingGeneralAdmExpenses, "Hello");
        aFinancial.put(CAMKeys.oMiscExpensesWrittenOff, "Hello");
        aFinancial.put(CAMKeys.oTransportOrCartage, "Hello");
        aFinancial.put(CAMKeys.oOpbdit, "Hello");
        aFinancial.put(CAMKeys.oOpbit, "Hello");
        aFinancial.put(CAMKeys.oInterestAndOtherFinanceCharges, "Hello");
        aFinancial.put(CAMKeys.oOpbt, "Hello");
        aFinancial.put(CAMKeys.oTotalNonOperatingIncome, "Hello");
        aFinancial.put(CAMKeys.oTotalNonOperatingExpense, "Hello");
        aFinancial.put(CAMKeys.oPBT, "Hello");
        aFinancial.put(CAMKeys.oTaxPaid, "Hello");
        aFinancial.put(CAMKeys.oPAT, "Hello");
        aFinancial.put(CAMKeys.oAdjPat, "Hello");
        aFinancial.put(CAMKeys.oEquityDividendPaid, "Hello");
        aFinancial.put(CAMKeys.oPartnersWithDrawl, "Hello");
        aFinancial.put(CAMKeys.oDividendTax, "Hello");
        aFinancial.put(CAMKeys.oDividendPreference, "Hello");
        aFinancial.put(CAMKeys.oRetainedProfit, "Hello");
        aFinancial.put(CAMKeys.oShareCapitalPaidUp, "Hello");
        aFinancial.put(CAMKeys.oSharePremiumAcc, "Hello");
        aFinancial.put(CAMKeys.oTotalShareCapital, "Hello");
        aFinancial.put(CAMKeys.oRevaluationReserve, "Hello");
        aFinancial.put(CAMKeys.oOtherReserves, "Hello");
        aFinancial.put(CAMKeys.oMiscExpNotWrittenOff, "Hello");
        aFinancial.put(CAMKeys.oTotalNetWorth, "Hello");
        aFinancial.put(CAMKeys.oBorrowingsFromAffiliatesAssociates, "Hello");
        aFinancial.put(CAMKeys.oShortTermBorrowingsFromOthers, "Hello");
        aFinancial.put(CAMKeys.oOtherTermLiabilities, "Hello");
        aFinancial.put(CAMKeys.oBorrowingsFromSubsidiaries, "Hello");
        aFinancial.put(CAMKeys.oDeferedTaxLiability, "Hello");
        aFinancial.put(CAMKeys.oLongTermProvision, "Hello");
        aFinancial.put(CAMKeys.oTotalTermLiabilities, "Hello");
        aFinancial.put(CAMKeys.oShortTermBorrowingsFromAssociates, "Hello");
        aFinancial.put(CAMKeys.oCreditorsandBillsPayable, "Hello");
        aFinancial.put(CAMKeys.oWorkingCapitalLimitfromBanks, "Hello");
        aFinancial.put(CAMKeys.oTotalRepaymentsDueWithinYear, "Hello");
        aFinancial.put(CAMKeys.oOtherCurrLiabilitiesAndProvisions, "Hello");
        aFinancial.put(CAMKeys.oProvisionForTaxation, "Hello");
        aFinancial.put(CAMKeys.oOthercurrentLiability1, "Hello");
        aFinancial.put(CAMKeys.oOthercurrentLiability2, "Hello");
        aFinancial.put(CAMKeys.oOthercurrentLiability3, "Hello");
        aFinancial.put(CAMKeys.oCurrentLiabilities, "Hello");
        aFinancial.put(CAMKeys.oTotalLiabilities, "Hello");
        aFinancial.put(CAMKeys.oBalanceSheetTotal, "Hello");
        aFinancial.put(CAMKeys.oGrossBlock, "Hello");
        aFinancial.put(CAMKeys.oAccumulatedDepreciation, "Hello");
        aFinancial.put(CAMKeys.oNetBlock, "Hello");
        aFinancial.put(CAMKeys.oCapitalWip, "Hello");
        aFinancial.put(CAMKeys.oDeferredRevenueExpenditure, "Hello");
        aFinancial.put(CAMKeys.oGovtAndOtherSecurities, "Hello");
        aFinancial.put(CAMKeys.oTotalOtherNonCurrentAssets, "Hello");
        aFinancial.put(CAMKeys.oDebtorsMoreThanSixMonths, "Hello");
        aFinancial.put(CAMKeys.oLoansAndAdvancess, "Hello");
        aFinancial.put(CAMKeys.oFixedDepositsWithBanks, "Hello");
        aFinancial.put(CAMKeys.oOtherNonCurrentAssets, "Hello");
        aFinancial.put(CAMKeys.oDeferredTaxAsset, "Hello");
        aFinancial.put(CAMKeys.oTotalCurrentAssets, "Hello");
        aFinancial.put(CAMKeys.oTotalInventory, "Hello");
        aFinancial.put(CAMKeys.oReceivablesOtherThanDeferred, "Hello");
        aFinancial.put(CAMKeys.oDeferredReceivables, "Hello");
        aFinancial.put(CAMKeys.oCashAndBankBalances, "Hello");
        aFinancial.put(CAMKeys.oOtherCurrentAssets, "Hello");
        aFinancial.put(CAMKeys.oAdvancesToSuppliers, "Hello");
        aFinancial.put(CAMKeys.oOthercurrentAsset1, "Hello");
        aFinancial.put(CAMKeys.oOthercurrentAsset2, "Hello");
        aFinancial.put(CAMKeys.oOthercurrentAsset3, "Hello");
        aFinancial.put(CAMKeys.oTotalAssets, "Hello");
        aFinancial.put(CAMKeys.oDifferenceFields, "Hello");
        aFinancial.put(CAMKeys.TOLTNW, "Hello");
        aFinancial.put(CAMKeys.RETURNONCAPITALEMPLOYED, "Hello");
        aFinancial.put(CAMKeys.EBIDTABYSALES, "Hello");
        aFinancial.put(CAMKeys.EBIDTAINTEREST, "Hello");
        aFinancial.put(CAMKeys.ASSETTURNOVERRATIO, "Hello");
        aFinancial.put(CAMKeys.CREDITORSTURNOVER, "Hello");
        aFinancial.put(CAMKeys.NETWORKINGCAPITAL, "Hello");
        aFinancial.put(CAMKeys.AVGCOLLECTIONPERIOD, "Hello");
        aFinancial.put(CAMKeys.AVERAGEDAYS, "Hello");
        aFinancial.put(CAMKeys.INVENTORYTOCOSTOFGOODSSOLD, "Hello");
        aFinancial.put(CAMKeys.CURRENTRATIO, "Hello");
        aFinancial.put(CAMKeys.LIQUIDITYRATIO, "Hello");
        aFinancial.put(CAMKeys.LONGDEBTTOEQUITY, "Hello");
        aFinancial.put(CAMKeys.EQUITY, "Hello");
        aFinancial.put(CAMKeys.INTERSETCOVERAGERATIO, "Hello");
        aFinancial.put(CAMKeys.DSCR, "Hello");
        aFinancial.put(CAMKeys.GROSSMARGINS, "Hello");
        aFinancial.put(CAMKeys.NETPROFITRATIO, "Hello");
        aFinancial.put(CAMKeys.CASHPROFITBYRATIO, "Hello");
        aFinancial.put(CAMKeys.GROWTHINSALES, "Hello");
        aFinancial.put(CAMKeys.GROWTHINPAT, "Hello");
        aFinancial.put(CAMKeys.CASHACCRUALS, "Hello");
        aFinancial.put(CAMKeys.oNetProfitAfterTax, "Hello");
        aFinancial.put(CAMKeys.oDepreciation, "Hello");
        aFinancial.put(CAMKeys.oSalaryPaidPromPartner, "Hello");
        aFinancial.put(CAMKeys.oInterestPaidPromoters, "Hello");
        aFinancial.put(CAMKeys.oProvisionTax, "Hello");
        aFinancial.put(CAMKeys.oInterest, "Hello");
        aFinancial.put(CAMKeys.oOtherIncome, "Hello");
        aFinancial.put(CAMKeys.oOperatingCashProfit, "Hello");
        aFinancial.put(CAMKeys.oTradeOtherReceivable, "Hello");
        aFinancial.put(CAMKeys.oInventories, "Hello");
        aFinancial.put(CAMKeys.oLoanAdvance, "Hello");
        aFinancial.put(CAMKeys.oOtherCurrentLiabilities, "Hello");
        aFinancial.put(CAMKeys.oWorkingCapitalChanges, "Hello");
        aFinancial.put(CAMKeys.oCashGenratedOperations, "Hello");
        aFinancial.put(CAMKeys.oTaxesPaid, "Hello");
        aFinancial.put(CAMKeys.oNetCashOperations, "Hello");
        return aFinancial;
    }

    public static Map<String, String> prepareGrowth(){
        Map<String, String> aGrowth = new HashMap<>();
        aGrowth.put(CAMKeys.aYears, "Hello");
        aGrowth.put(CAMKeys.oSales, "Hello");
        aGrowth.put(CAMKeys.oExciseDuty, "Hello");
        aGrowth.put(CAMKeys.oNetSales, "Hello");
        aGrowth.put(CAMKeys.oExportIncentives, "Hello");
        aGrowth.put(CAMKeys.oTotalOperatingIncome, "Hello");

        aGrowth.put(CAMKeys.oRawMaterialsImported, "Hello");
        aGrowth.put(CAMKeys.oOtherMfgExpenses, "Hello");
        aGrowth.put(CAMKeys.oRepairsAndMaintenance, "Hello");
        aGrowth.put(CAMKeys.oCostOfGoodsSold, "Hello");
        aGrowth.put(CAMKeys.oCostOfGoodsSold, "Hello");
        aGrowth.put(CAMKeys.oGrossProfits, "Hello");
        aGrowth.put(CAMKeys.oSellingGeneralAdmExpenses, "Hello");
        aGrowth.put(CAMKeys.oMiscExpensesWrittenOff, "Hello");
        aGrowth.put(CAMKeys.oTransportOrCartage, "Hello");
        aGrowth.put(CAMKeys.oOpbdit, "Hello");
        aGrowth.put(CAMKeys.oOpbit, "Hello");
        aGrowth.put(CAMKeys.oInterestAndOtherFinanceCharges, "Hello");
        aGrowth.put(CAMKeys.oOpbt, "Hello");
        aGrowth.put(CAMKeys.oTotalNonOperatingIncome, "Hello");
        aGrowth.put(CAMKeys.oTotalNonOperatingExpense, "Hello");
        aGrowth.put(CAMKeys.oPBT, "Hello");
        aGrowth.put(CAMKeys.oTaxPaid, "Hello");
        aGrowth.put(CAMKeys.oPAT, "Hello");
        aGrowth.put(CAMKeys.oAdjPat, "Hello");
        aGrowth.put(CAMKeys.oEquityDividendPaid, "Hello");
        aGrowth.put(CAMKeys.oPartnersWithDrawl, "Hello");
        aGrowth.put(CAMKeys.oDividendTax, "Hello");
        aGrowth.put(CAMKeys.oDividendPreference, "Hello");
        aGrowth.put(CAMKeys.oRetainedProfit, "Hello");
        aGrowth.put(CAMKeys.oShareCapitalPaidUp, "Hello");
        aGrowth.put(CAMKeys.oSharePremiumAcc, "Hello");
        aGrowth.put(CAMKeys.oTotalShareCapital, "Hello");
        aGrowth.put(CAMKeys.oRevaluationReserve, "Hello");
        aGrowth.put(CAMKeys.oOtherReserves, "Hello");
        aGrowth.put(CAMKeys.oMiscExpNotWrittenOff, "Hello");
        aGrowth.put(CAMKeys.oTotalNetWorth, "Hello");
        aGrowth.put(CAMKeys.oBorrowingsFromAffiliatesAssociates, "Hello");
        aGrowth.put(CAMKeys.oShortTermBorrowingsFromOthers, "Hello");
        aGrowth.put(CAMKeys.oOtherTermLiabilities, "Hello");
        aGrowth.put(CAMKeys.oBorrowingsFromSubsidiaries, "Hello");
        aGrowth.put(CAMKeys.oDeferedTaxLiability, "Hello");
        aGrowth.put(CAMKeys.oLongTermProvision, "Hello");
        aGrowth.put(CAMKeys.oTotalTermLiabilities, "Hello");
        aGrowth.put(CAMKeys.oShortTermBorrowingsFromAssociates, "Hello");
        aGrowth.put(CAMKeys.oCreditorsandBillsPayable, "Hello");
        aGrowth.put(CAMKeys.oWorkingCapitalLimitfromBanks, "Hello");
        aGrowth.put(CAMKeys.oTotalRepaymentsDueWithinYear, "Hello");
        aGrowth.put(CAMKeys.oOtherCurrLiabilitiesAndProvisions, "Hello");
        aGrowth.put(CAMKeys.oProvisionForTaxation, "Hello");
        aGrowth.put(CAMKeys.oOthercurrentLiability1, "Hello");
        aGrowth.put(CAMKeys.oOthercurrentLiability2, "Hello");
        aGrowth.put(CAMKeys.oOthercurrentLiability3, "Hello");
        aGrowth.put(CAMKeys.oCurrentLiabilities, "Hello");
        aGrowth.put(CAMKeys.oTotalLiabilities, "Hello");
        aGrowth.put(CAMKeys.oBalanceSheetTotal, "Hello");
        aGrowth.put(CAMKeys.oGrossBlock, "Hello");
        aGrowth.put(CAMKeys.oAccumulatedDepreciation, "Hello");
        aGrowth.put(CAMKeys.oNetBlock, "Hello");
        aGrowth.put(CAMKeys.oCapitalWip, "Hello");
        aGrowth.put(CAMKeys.oDeferredRevenueExpenditure, "Hello");
        aGrowth.put(CAMKeys.oGovtAndOtherSecurities, "Hello");
        aGrowth.put(CAMKeys.oTotalOtherNonCurrentAssets, "Hello");
        aGrowth.put(CAMKeys.oDebtorsMoreThanSixMonths, "Hello");
        aGrowth.put(CAMKeys.oLoansAndAdvancess, "Hello");
        aGrowth.put(CAMKeys.oFixedDepositsWithBanks, "Hello");
        aGrowth.put(CAMKeys.oOtherNonCurrentAssets, "Hello");
        aGrowth.put(CAMKeys.oDeferredTaxAsset, "Hello");
        aGrowth.put(CAMKeys.oTotalCurrentAssets, "Hello");
        aGrowth.put(CAMKeys.oTotalInventory, "Hello");
        aGrowth.put(CAMKeys.oReceivablesOtherThanDeferred, "Hello");
        aGrowth.put(CAMKeys.oDeferredReceivables, "Hello");
        aGrowth.put(CAMKeys.oCashAndBankBalances, "Hello");
        aGrowth.put(CAMKeys.oOtherCurrentAssets, "Hello");
        aGrowth.put(CAMKeys.oAdvancesToSuppliers, "Hello");
        aGrowth.put(CAMKeys.oOthercurrentAsset1, "Hello");
        aGrowth.put(CAMKeys.oOthercurrentAsset2, "Hello");
        aGrowth.put(CAMKeys.oOthercurrentAsset3, "Hello");
        aGrowth.put(CAMKeys.oTotalAssets, "Hello");
        aGrowth.put(CAMKeys.oDifferenceFields, "Hello");
        aGrowth.put(CAMKeys.TOLTNW, "Hello");
        aGrowth.put(CAMKeys.RETURNONCAPITALEMPLOYED, "Hello");
        aGrowth.put(CAMKeys.EBIDTABYSALES, "Hello");
        aGrowth.put(CAMKeys.EBIDTAINTEREST, "Hello");
        aGrowth.put(CAMKeys.ASSETTURNOVERRATIO, "Hello");
        aGrowth.put(CAMKeys.CREDITORSTURNOVER, "Hello");
        aGrowth.put(CAMKeys.NETWORKINGCAPITAL, "Hello");
        aGrowth.put(CAMKeys.AVGCOLLECTIONPERIOD, "Hello");
        aGrowth.put(CAMKeys.AVERAGEDAYS, "Hello");
        aGrowth.put(CAMKeys.INVENTORYTOCOSTOFGOODSSOLD, "Hello");
        aGrowth.put(CAMKeys.CURRENTRATIO, "Hello");
        aGrowth.put(CAMKeys.LIQUIDITYRATIO, "Hello");
        aGrowth.put(CAMKeys.LONGDEBTTOEQUITY, "Hello");
        aGrowth.put(CAMKeys.EQUITY, "Hello");
        aGrowth.put(CAMKeys.INTERSETCOVERAGERATIO, "Hello");
        aGrowth.put(CAMKeys.DSCR, "Hello");
        aGrowth.put(CAMKeys.GROSSMARGINS, "Hello");
        aGrowth.put(CAMKeys.NETPROFITRATIO, "Hello");
        aGrowth.put(CAMKeys.CASHPROFITBYRATIO, "Hello");
        aGrowth.put(CAMKeys.GROWTHINSALES, "Hello");
        aGrowth.put(CAMKeys.GROWTHINPAT, "Hello");
        aGrowth.put(CAMKeys.CASHACCRUALS, "Hello");
        aGrowth.put(CAMKeys.oNetProfitAfterTax, "Hello");
        aGrowth.put(CAMKeys.oDepreciation, "Hello");
        aGrowth.put(CAMKeys.oSalaryPaidPromPartner, "Hello");
        aGrowth.put(CAMKeys.oInterestPaidPromoters, "Hello");
        aGrowth.put(CAMKeys.oProvisionTax, "Hello");
        aGrowth.put(CAMKeys.oInterest, "Hello");
        aGrowth.put(CAMKeys.oOtherIncome, "Hello");
        aGrowth.put(CAMKeys.oOperatingCashProfit, "Hello");
        aGrowth.put(CAMKeys.oTradeOtherReceivable, "Hello");
        aGrowth.put(CAMKeys.oInventories, "Hello");
        aGrowth.put(CAMKeys.oLoanAdvance, "Hello");
        aGrowth.put(CAMKeys.oOtherCurrentLiabilities, "Hello");
        aGrowth.put(CAMKeys.oWorkingCapitalChanges, "Hello");
        aGrowth.put(CAMKeys.oCashGenratedOperations, "Hello");
        aGrowth.put(CAMKeys.oTaxesPaid, "Hello");
        aGrowth.put(CAMKeys.oNetCashOperations, "Hello");
        return aGrowth;
    }

}
